version: '3.2'
services:
  # rabbitmq:
  #   image: rabbitmq:management
  #   hostname: rabbitmq
  #   restart: on-failure
  #   command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
  #   environment:
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: admin
  #   ports:
  #     - 15672:15672
  #   volumes:
  #     - ./docker/rabbitmq/:/var/lib/rabbitmq
  #     - ./docker/rabbitmq/log:/var/log/rabbitmq

  server:
    hostname: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - ./server/:/usr/src/app

  client:
    hostname: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80

  # consumer:
  #   hostname: consumer
  #   build:
  #     context: ./consumer/
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   volumes:
  #     - ./consumer/:/usr/src/app
