version: '3.2'
services:
  mysql:
    image: mysql:8.3.0
    hostname: mysql
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/:/var/lib/mysql

  http_server:
    hostname: http_server
    build:
      context: ./http_server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./http_server/:/usr/src/app

  # rabbitmq:
  #   image: rabbitmq:management
  #   hostname: rabbitmq
  #   restart: on-failure
  #   command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
  #   environment:
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: admin
  #   ports:
  #     - 15672:15672
  #   volumes:
  #     - ./docker/rabbitmq/:/var/lib/rabbitmq
  #     - ./docker/rabbitmq/log:/var/log/rabbitmq

  # websocket_server:
  #   hostname: websocket_server
  #   build:
  #     context: ./websocket_server/
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./websocket_server/:/usr/src/app

  # consumer:
  #   hostname: consumer
  #   build:
  #     context: ./consumer/
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   volumes:
  #     - ./consumer/:/usr/src/app
